name: "HW45 Tests"

on:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

jobs:
  test-hw45:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    strategy:
      matrix:
        python-version: ["3.12", "3.13"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      working-directory: hw45
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      
    - name: Run tests with saving coverage
      working-directory: hw45
      env:
        PYTHONPATH: ${{ github.workspace }}/hw45
      run: |
        export PYTHONPATH=$PYTHONPATH:$(pwd)
        pytest
      
    - name: Check coverage threshold
      working-directory: hw45
      run: |
        python -m coverage run -m pytest
        python -m coverage report --fail-under=95
